import React from 'react';

export const defaultLanguageLabels = {
  applicationSidebar: {
    MEMBERS: 'MEMBERS',
    MEMBERSHIP_FEE: 'MEMBERSHIP_FEE',
    ORGANIZATION_DETAILS: 'ORGANIZATION_DETAILS',
    ORGANIZATIONS: 'ORGANIZATIONS',
    REPORTS: 'REPORTS',
  },
  memberForm: {
    NAME: 'MEMBER_FORM_NAME',
    ORGANIZATION: 'MEMBER_FORM_ORGANIZATION',
    BIRTH_DATE: 'MEMBER_FORM_BIRTH_DATE',
    ADDRESS: 'MEMBER_FORM_ADDRESS',
    PHONE_NUMBER: 'MEMBER_FORM_PHONE_NUMBER',
    EMAIL: 'MEMBER_FORM_EMAIL',
    GENDER: 'MEMBER_FORM_GENDER',
    REGISTRATION_DATE: 'MEMBER_FORM_REGISTRATION_DATE',
    MEMBER_CATEGORY: 'MEMBER_FORM_MEMBER_CATEGORY',
    STATUS: 'MEMBER_FORM_STATUS',
  },
  memberTable: {
    NAME: 'NAME',
    ID: 'ID',
    ORGANIZATION: 'ORGANIZATION',
    ACTIONS: 'ACTIONS',
  },
  memberPage: {
    HEADER: 'EXISTING_MEMBER_PAGE_HEADER',
  },
  membersPage: {
    HEADER: 'MEMBERS_PAGE_HEADER',
    NEW_MEMBER: 'NEW_MEMBER',
  },
  newMemberPage: {
    HEADER: 'NEW_MEMBER_PAGE_HEADER',
    SAVE_BUTTON: 'MEMBER_FORM_SAVE_BUTTON',
    SAVE_BUTTON_AND_CREATE_NEW: 'MEMBER_FORM_SAVE_BUTTON_AND_CREATE_NEW',
  },
};

export const LanguageContext = React.createContext(defaultLanguageLabels);
